
cd "/global/ioc/boot/"

< cdCommands

cd topbin

ld < gretDet.munch

cd top

dbLoadDatabase("dbd/gretDet.dbd",0,0)
gretDet_registerRecordDeviceDriver(pdbbase)
taskDelay(100)

cd top

########## Load record intances ##################

## Load Register Templates
dbLoadRecords("db/MDigRegisters.template", "CRATE=02,BOARD=MDIG1")
dbLoadRecords("db/MDigRegisters.template", "CRATE=02,BOARD=MDIG2")
dbLoadRecords("db/MDigRegisters.template", "CRATE=02,BOARD=MDIG3")
dbLoadRecords("db/MDigRegisters.template", "CRATE=02,BOARD=MDIG4")
taskDelay(100)

## Load Users Templates
dbLoadRecords("db/MDigUser.template", "CRATE=02,BOARD=MDIG1")
dbLoadRecords("db/MDigUser.template", "CRATE=02,BOARD=MDIG2")
dbLoadRecords("db/MDigUser.template", "CRATE=02,BOARD=MDIG3")
dbLoadRecords("db/MDigUser.template", "CRATE=02,BOARD=MDIG4")
taskDelay(100)
 
## Load daqSegment2.template for each digitizer in crate
dbLoadRecords("db/daqSegment2.template", "CRATE=02,BOARD=MDIG1")
dbLoadRecords("db/daqSegment2.template", "CRATE=02,BOARD=MDIG2")
dbLoadRecords("db/daqSegment2.template", "CRATE=02,BOARD=MDIG3")
dbLoadRecords("db/daqSegment2.template", "CRATE=02,BOARD=MDIG4")
taskDelay(100)

## These pvs are for running a sender/sorter/fiforeader on crate
dbLoadRecords("db/daqCrate.template","CRATE=02")
taskDelay(100)

## Loading Digitizer Globals as generated by spreadsheet.
dbLoadRecords("db/dgsGlobals_DGS_VME02.db")
taskDelay(100)

############# before loading any board, initialize the DAQ board structure in the driver.
InitializeDaqBoardStructure()

####### Now initialize slot-board # mapping of digitizers #####################
# Need to give (PortName,Card#,Slot#)
asynDigitizerConfig("MDIG1",0,3)
asynDigitizerConfig("MDIG2",1,4)
asynDigitizerConfig("MDIG3",2,5)
asynDigitizerConfig("MDIG4",3,6)

# Allow access to hardware through "back door" PVs
asynDebugConfig("DBG",0)

cd startup

##################### Run the dreaded iocInit()
iocInit()

dumpFIFO = 0

#New feature for initializing Quueing system
setupFIFOReader()

## assign user package data to each digitizer in crate
# This is now done in the setup script.
# If the IOC reboots we do NOT want the user_package_data to ever be 
# changed by a source that is not expected, such as anything outside of
# the run setup script.

dbpf "VME02:MDIG1:user_package_data","105"
dbpf "VME02:MDIG2:user_package_data","106"
dbpf "VME02:MDIG3:user_package_data","107"
dbpf "VME02:MDIG4:user_package_data","108"

seq &inLoop,"CRATE=02,B0=MDIG1,B1=MDIG2,B2=MDIG3,B3=MDIG4,B4=X,B5=X,B6=X"
taskDelay(100)
seq &outLoop,"CRATE=02"
taskDelay(100)
seq &MiniSender,"CRATE=02"


