/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.21
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#include "Python.h"

/*************************************************************** -*- c -*-
 * python/precommon.swg
 *
 * Rename all exported symbols from common.swg, to avoid symbol
 * clashes if multiple interpreters are included
 *
 ************************************************************************/

#define SWIG_TypeRegister    SWIG_Python_TypeRegister
#define SWIG_TypeCheck       SWIG_Python_TypeCheck
#define SWIG_TypeCast        SWIG_Python_TypeCast
#define SWIG_TypeDynamicCast SWIG_Python_TypeDynamicCast
#define SWIG_TypeName        SWIG_Python_TypeName
#define SWIG_TypeQuery       SWIG_Python_TypeQuery
#define SWIG_TypeClientData  SWIG_Python_TypeClientData
#define SWIG_PackData        SWIG_Python_PackData 
#define SWIG_UnpackData      SWIG_Python_UnpackData 


/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if defined(_MSC_VER) || defined(__GNUC__)
#    if defined(STATIC_LINKED)
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) extern a
#    else
#      define SWIGEXPORT(a) __declspec(dllexport) a
#      define SWIGIMPORT(a) extern a
#    endif
#  else
#    if defined(__BORLANDC__)
#      define SWIGEXPORT(a) a _export
#      define SWIGIMPORT(a) a _export
#    else
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) a
#    endif
#  endif
#else
#  define SWIGEXPORT(a) a
#  define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#  define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#  define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);
SWIGIMPORT(char *)           SWIG_PackData(char *, void *, int);
SWIGIMPORT(char *)           SWIG_UnpackData(char *, void *, int);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientData(tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

#endif

#ifdef __cplusplus
}
#endif

/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Flags for pointer conversion */

#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

/* Exception handling in wrappers */
#define SWIG_fail   goto fail

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

/* Common SWIG API */
#define SWIG_ConvertPtr(obj, pp, type, flags) \
  SWIG_Python_ConvertPtr(obj, pp, type, flags)
#define SWIG_NewPointerObj(p, type, flags) \
  SWIG_Python_NewPointerObj(p, type, flags)
#define SWIG_MustGetPtr(p, type, argnum, flags) \
  SWIG_Python_MustGetPtr(p, type, argnum, flags)

/* Python-specific SWIG API */
#define SWIG_newvarlink() \
  SWIG_Python_newvarlink()
#define SWIG_addvarlink(p, name, get_attr, set_attr) \
  SWIG_Python_addvarlink(p, name, get_attr, set_attr)
#define SWIG_ConvertPacked(obj, ptr, sz, ty, flags) \
  SWIG_Python_ConvertPacked(obj, ptr, sz, ty, flags)
#define SWIG_NewPackedObj(ptr, sz, type) \
  SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_InstallConstants(d, constants) \
  SWIG_Python_InstallConstants(d, constants)

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(int)               SWIG_Python_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPointerObj(void *, swig_type_info *,int own);
SWIGIMPORT(void *)            SWIG_Python_MustGetPtr(PyObject *, swig_type_info *, int, int);
SWIGIMPORT(PyObject *)        SWIG_Python_newvarlink(void);
SWIGIMPORT(void)              SWIG_Python_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGIMPORT(int)               SWIG_Python_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPackedObj(void *, int sz, swig_type_info *);
SWIGIMPORT(void)              SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]);

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",              /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_Python_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_Python_addvarlink(PyObject *p, char *name, PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;
  static PyObject *SWIG_this = 0;
  int    newref = 0;
  PyObject  *pyobj = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  }  
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }

  if ((pyobj) && (flags & SWIG_POINTER_DISOWN)) {
    PyObject *zero = PyInt_FromLong(0);
    PyObject_SetAttrString(pyobj,(char*)"thisown",zero);
    Py_DECREF(zero);
  }
  return 0;

type_error:
  if (flags & SWIG_POINTER_EXCEPTION) {
    if (ty && c) {
      char *temp = (char *) malloc(64+strlen(ty->name)+strlen(c));
      sprintf(temp,"Type error. Got %s, expected %s", c, ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a pointer value, signal an exception on a type mismatch */
SWIGRUNTIME(void *)
SWIG_Python_MustGetPtr(PyObject *obj, swig_type_info *ty, int argnum, int flags) {
  void *result;
  SWIG_Python_ConvertPtr(obj, &result, ty, flags | SWIG_POINTER_EXCEPTION);
  return result;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty && c) {
      char *temp = (char *) malloc(64+strlen(ty->name)+strlen(c));
      sprintf(temp,"Type error. Got %s, expected %s", c, ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_Python_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (inst) {
      if (own) {
        PyObject *n = PyInt_FromLong(1);
        PyObject_SetAttrString(inst,(char*)"thisown",n);
        Py_DECREF(n);
      }
      robj = inst;
    }
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_Python_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) { PyErr_SetString(PyExc_RuntimeError, (char *) msg ); goto fail; } else

#ifdef __cplusplus
}
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_chid swig_types[0] 
#define  SWIGTYPE_p_event_handler_args swig_types[1] 
#define  SWIGTYPE_p_evid swig_types[2] 
#define  SWIGTYPE_p_void swig_types[3] 
#define  SWIGTYPE_p_CA_SYNC_GID swig_types[4] 
#define  SWIGTYPE_p_dbr_float_t swig_types[5] 
static swig_type_info *swig_types[7];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= _ca.so
  ------------------------------------------------*/
#define SWIG_init    init_ca

#define SWIG_name    "_ca"

#include "alarmString.h"
#include "cadef.h"
 
#include "fdmgr.h"
fdctx *pfdctx;
static struct timeval twenty_seconds	= {20, 0};
static struct timeval fifteen_seconds	= {15, 0};
static struct timeval one_second	= { 0, 1000000};

#include "ca_internal_functions.c"



void caVersion()
{
    printf("caPython: version v00-02-01\n");
    printf("Supports EPICS R3.12 CA Client API\n");
    printf("%s\n", ca_version());
} /* end caVersion() */


chid *new_chid()
{
    void *pspace;
    pspace = malloc(sizeof(chid *));
    if (NULL == pspace)
	PyErr_NoMemory();
    return pspace;
} 

void free_chid(chid *pchid)
{
    free(pchid);
} 

evid *new_evid()
{
    void *pspace;
    pspace = malloc(sizeof(evid *));
    if (NULL == pspace)
	PyErr_NoMemory();
    return pspace;
} 

void free_evid(evid *pevid)
{
    free(pevid);
} 

int close_channel(chid chId)
{
    /* The callback data is stored here and must
     * be removed when the channel is closed
     */
    if (ca_puser(chId) != NULL) {
        Py_DECREF((PyObject *)ca_puser(chId));
    }
    
    return ca_clear_channel(chId);

} 

int close_event(evid evId)
{
    /* The callback data is stored here and must
     * be removed when the channel is closed
     */
    if (ca_puser(ca_evid_to_chid(evId)) != NULL) {
        Py_DECREF((PyObject *)ca_puser(ca_evid_to_chid(evId)));
    }
    
    return ca_clear_event(evId);

} 

int ca_field_type_macro(chid chId) {
    return ca_field_type(chId);
} 

unsigned ca_element_count_macro(chid chId) {
    return ca_element_count(chId);
} 

const char *ca_name_macro(chid chId) {
    return ca_name(chId);
} 

void *ca_puser_macro(chid chId) {
    return ca_puser(chId);
} 

enum channel_state ca_state_macro(chid chId) {
    return ca_state(chId);
} 

const char *ca_message_macro(int status) {
    return ca_message(status);
} 

const char *ca_host_name_macro(chid chId) {
    return ca_host_name(chId);
} 

int ca_read_access_macro(chid chId) {
    return ca_read_access(chId);
} 

int ca_write_access_macro(chid chId) {
    return ca_write_access(chId);
} 

unsigned dbr_size_n_macro(chtype type, int count) {
    return dbr_size_n(type, count);
} 

unsigned dbr_size_macro(chtype type) {
    return dbr_size[type];
} 

unsigned dbr_value_size_macro(chtype type) {
    return dbr_value_size[type];
} 

int valid_db_req_macro(int x) {
    return VALID_DB_REQ(x);
} 

int invalid_db_req_macro(int x) {
    return INVALID_DB_REQ(x);
} 

const char *dbr_text_macro(int x) {
    return dbr_type_to_text(x);
} 

const char *dbf_text_macro(int x) {
    return dbf_type_to_text(x);
} 

int dbf_type_to_DBR_macro(int x) {
    return dbf_type_to_DBR(x);
} 

int dbf_type_to_DBR_STS_macro(int x) {
    return dbf_type_to_DBR_STS(x);
} 

int dbf_type_to_DBR_TIME_macro(int x) {
    return dbf_type_to_DBR_TIME(x);
} 

int dbf_type_to_DBR_GR_macro(int x) {
    return dbf_type_to_DBR_GR(x);
} 

int dbf_type_to_DBR_CTRL_macro(int x) {
    return dbf_type_to_DBR_CTRL(x);
} 

int dbr_type_is_valid_macro(int x) {
    return dbr_type_is_valid(x);
} 

int dbr_type_is_plain_macro(int x) {
    return dbr_type_is_plain(x);
} 

int dbr_type_is_STS_macro(int x) {
    return dbr_type_is_STS(x);
} 

int dbr_type_is_TIME_macro(int x) {
    return dbr_type_is_TIME(x);
} 

int dbr_type_is_GR_macro(int x) {
    return dbr_type_is_GR(x);
} 

int dbr_type_is_CTRL_macro(int x) {
    return dbr_type_is_CTRL(x);
} 

const char *alarmSeverityString_macro(int x) {
    return alarmSeverityString[x];
} 

const char *alarmStatusString_macro(int x) {
    return alarmStatusString[x];
} 

void fdmgr_start() {
    /* printf("fdmgr_start: fdmgr_init()\n"); */
    pfdctx = fdmgr_init();
    
    if(!pfdctx)
	printf("fdmgr_start: fdmgr_init() failed\n");

    SEVCHK(ca_add_fd_registration(fd_register, pfdctx), 
		"fdmgr_start: ca_add_fd_registration failed");

    /* printf("fdmgr_start: fdmgr_add_timeout()\n"); */
    fdmgr_add_timeout(pfdctx, &one_second, capollfunc, (void *)NULL);

} 

void fdmgr_pend() {
    fdmgr_pend_event(pfdctx, &twenty_seconds);
} 


#include <ctype.h>

/*------------------------------------------------------------------
  ptrcast(value,type)

  Constructs a new pointer value.   Value may either be a string
  or an integer. Type is a string corresponding to either the
  C datatype or mangled datatype.

  ptrcast(0,"Vector *")
               or
  ptrcast(0,"Vector_p")   
  ------------------------------------------------------------------ */

static PyObject *captrcast(PyObject *_PTRVALUE, char *type) {

  char *r,*s;
  void *ptr;
  PyObject *obj;
  char *typestr,*c;

  /* Produce a "mangled" version of the type string.  */

  typestr = (char *) malloc(strlen(type)+2);
  
  /* Go through and munge the typestring */
  
  r = typestr;
  *(r++) = '_';
  c = type;
  while (*c) {
    if (!isspace(*c)) {
      if ((*c == '*') || (*c == '&')) {
	*(r++) = 'p';
      }
      else *(r++) = *c;
    } else {
        *(r++) = '_';
    }
    c++;
  }
  *(r++) = 0;

  /* Check to see what kind of object _PTRVALUE is */
  
  if (PyInt_Check(_PTRVALUE)) {
    ptr = (void *) PyInt_AsLong(_PTRVALUE);
    /* Received a numerical value. Make a pointer out of it */
    r = (char *) malloc(strlen(typestr)+22);
    if (ptr) {
      SWIG_MakePtr(r, ptr, typestr);
    } else {
      sprintf(r,"_0%s",typestr);
    }
    obj = PyString_FromString(r);
    free(r);
  } else if (PyString_Check(_PTRVALUE)) {
    /* Have a real pointer value now.  Try to strip out the pointer
       value */
    s = PyString_AsString(_PTRVALUE);
    r = (char *) malloc(strlen(type)+22);
    
    /* Now extract the pointer value */
    if (!SWIG_GetPtr(s,&ptr,0)) {
      if (ptr) {
	SWIG_MakePtr(r,ptr,typestr);
      } else {
	sprintf(r,"_0%s",typestr);
      }
      obj = PyString_FromString(r);
    } else {
      obj = NULL;
    }
    free(r);
  } else {
    obj = NULL;
  }
  free(typestr);
  if (!obj) 
    PyErr_SetString(PyExc_TypeError,"Type error in ptrcast. Argument is not a valid pointer value.");
  return obj;
}

/*------------------------------------------------------------------
  ptrvalue(ptr,type = 0)

  Attempts to dereference a pointer value.  If type is given, it 
  will try to use that type.  Otherwise, this function will attempt
  to "guess" the proper datatype by checking against all of the 
  builtin C datatypes. 
  ------------------------------------------------------------------ */

static PyObject *captrvalue(PyObject *_PTRVALUE, int index, char *type) {
  void     *ptr;
  char     *s;
  PyObject *obj;

  if (!PyString_Check(_PTRVALUE)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrvalue. Argument is not a valid pointer value.");
    return NULL;
  }
  s = PyString_AsString(_PTRVALUE);
  if (SWIG_GetPtr(s,&ptr,0)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrvalue. Argument is not a valid pointer value.");
    return NULL;
  }

  /* If no datatype was passed, try a few common datatypes first */

  if (!type) {

    /* No datatype was passed.   Type to figure out if it's a common one */

    if (!SWIG_GetPtr(s,&ptr,"_int_p")) {
      type = "int";
    } else if (!SWIG_GetPtr(s,&ptr,"_double_p")) {
      type = "double";
    } else if (!SWIG_GetPtr(s,&ptr,"_short_p")) {
      type = "short";
    } else if (!SWIG_GetPtr(s,&ptr,"_long_p")) {
      type = "long";
    } else if (!SWIG_GetPtr(s,&ptr,"_float_p")) {
      type = "float";
    } else if (!SWIG_GetPtr(s,&ptr,"_char_p")) {
      type = "char";
    } else if (!SWIG_GetPtr(s,&ptr,"_char_pp")) {
      type = "char *";
    } else {
      type = "unknown";
    }
  }

  if (!ptr) {
    PyErr_SetString(PyExc_TypeError,"Unable to dereference NULL pointer.");
    return NULL;
  }

  /* Now we have a datatype.  Try to figure out what to do about it */
  if (strcmp(type,"int") == 0) {
    obj = PyInt_FromLong((long) *(((int *) ptr) + index));
  } else if (strcmp(type,"double") == 0) {
    obj = PyFloat_FromDouble((double) *(((double *) ptr)+index));
  } else if (strcmp(type,"short") == 0) {
    obj = PyInt_FromLong((long) *(((short *) ptr)+index));
  } else if (strcmp(type,"long") == 0) {
    obj = PyInt_FromLong((long) *(((long *) ptr)+index));
  } else if (strcmp(type,"float") == 0) {
    obj = PyFloat_FromDouble((double) *(((float *) ptr)+index));
  } else if (strcmp(type,"char") == 0) {
    obj = PyString_FromString(((char *) ptr)+index);
  } else if (strcmp(type,"char *") == 0) {
    char *c = *(((char **) ptr)+index);
    if (c) obj = PyString_FromString(c);
    else obj = PyString_FromString("NULL");
  } else {
    PyErr_SetString(PyExc_TypeError,"Unable to dereference unsupported datatype.");
    return NULL;
  }
  return obj;
}

/*------------------------------------------------------------------
  ptrcreate(type,value = 0,numelements = 1)

  Attempts to create a new object of given type.  Type must be
  a basic C datatype.  Will not create complex objects.
  ------------------------------------------------------------------ */

static PyObject *captrcreate(char *type, PyObject *_PYVALUE, int numelements) {
  void     *ptr;
  PyObject *obj;
  int       sz;
  char     *cast;
  char      temp[40];

  /* Check the type string against a variety of possibilities */

  if (strcmp(type,"int") == 0) {
    sz = sizeof(int)*numelements;
    cast = "_int_p";
  } else if (strcmp(type,"short") == 0) {
    sz = sizeof(short)*numelements;
    cast = "_short_p";
  } else if (strcmp(type,"long") == 0) {
    sz = sizeof(long)*numelements;
    cast = "_long_p";
  } else if (strcmp(type,"double") == 0) {
    sz = sizeof(double)*numelements;
    cast = "_double_p";
  } else if (strcmp(type,"float") == 0) {
    sz = sizeof(float)*numelements;
    cast = "_float_p";
  } else if (strcmp(type,"char") == 0) {
    sz = sizeof(char)*numelements;
    cast = "_char_p";
  } else if (strcmp(type,"char *") == 0) {
    sz = sizeof(char *)*(numelements+1);
    cast = "_char_pp";
  } else {
    PyErr_SetString(PyExc_TypeError,"Unable to create unknown datatype."); 
    return NULL;
  }
   
  /* Create the new object */
  
  ptr = (void *) malloc(sz);
  if (!ptr) {
    PyErr_SetString(PyExc_MemoryError,"Out of memory in swig_create."); 
    return NULL;
  }

  /* Now try to set its default value */

  if (_PYVALUE) {
    if (strcmp(type,"int") == 0) {
      int *ip,i,ivalue;
      ivalue = (int) PyInt_AsLong(_PYVALUE);
      ip = (int *) ptr;
      for (i = 0; i < numelements; i++)
	ip[i] = ivalue;
    } else if (strcmp(type,"short") == 0) {
      short *ip,ivalue;
      int i;
      ivalue = (short) PyInt_AsLong(_PYVALUE);
      ip = (short *) ptr;
      for (i = 0; i < numelements; i++)
	ip[i] = ivalue;
    } else if (strcmp(type,"long") == 0) {
      long *ip,ivalue;
      int i;
      ivalue = (long) PyInt_AsLong(_PYVALUE);
      ip = (long *) ptr;
      for (i = 0; i < numelements; i++)
	ip[i] = ivalue;
    } else if (strcmp(type,"double") == 0) {
      double *ip,ivalue;
      int i;
      ivalue = (double) PyFloat_AsDouble(_PYVALUE);
      ip = (double *) ptr;
      for (i = 0; i < numelements; i++)
	ip[i] = ivalue;
    } else if (strcmp(type,"float") == 0) {
      float *ip,ivalue;
      int i;
      ivalue = (float) PyFloat_AsDouble(_PYVALUE);
      ip = (float *) ptr;
      for (i = 0; i < numelements; i++)
	ip[i] = ivalue;
    } else if (strcmp(type,"char") == 0) {
      char *ip,*ivalue;
      ivalue = (char *) PyString_AsString(_PYVALUE);
      ip = (char *) ptr;
      strcpy(ip, ivalue);
      /* strncpy(ip,ivalue,numelements-1); */
    } else if (strcmp(type,"char *") == 0) {
      char **ip, *ivalue;
      int  i;
      ivalue = (char *) PyString_AsString(_PYVALUE);
      ip = (char **) ptr;
      for (i = 0; i < numelements; i++) {
	if (ivalue) {
	  ip[i] = (char *) malloc(strlen(ivalue)+1);
	  strcpy(ip[i],ivalue);
	} else {
	  ip[i] = 0;
	}
      }
      ip[numelements] = 0;
    }
  } 
  /* Create the pointer value */
  
  SWIG_MakePtr(temp,ptr,cast);
  obj = PyString_FromString(temp);
  return obj;
}


/*------------------------------------------------------------------
  ptrset(ptr,value,index = 0,type = 0)

  Attempts to set the value of a pointer variable.  If type is
  given, we will use that type.  Otherwise, we'll guess the datatype.
  ------------------------------------------------------------------ */

static PyObject *captrset(PyObject *_PTRVALUE, PyObject *_PYVALUE, int index, char *type) {
  void     *ptr;
  char     *s;

  if (!PyString_Check(_PTRVALUE)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrset. Argument is not a valid pointer value.");
    return NULL;
  }
  s = PyString_AsString(_PTRVALUE);
  if (SWIG_GetPtr(s,&ptr,0)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrset. Argument is not a valid pointer value.");
    return NULL;
  }

  /* If no datatype was passed, try a few common datatypes first */

  if (!type) {

    /* No datatype was passed.   Type to figure out if it's a common one */

    if (!SWIG_GetPtr(s,&ptr,"_int_p")) {
      type = "int";
    } else if (!SWIG_GetPtr(s,&ptr,"_double_p")) {
      type = "double";
    } else if (!SWIG_GetPtr(s,&ptr,"_short_p")) {
      type = "short";
    } else if (!SWIG_GetPtr(s,&ptr,"_long_p")) {
      type = "long";
    } else if (!SWIG_GetPtr(s,&ptr,"_float_p")) {
      type = "float";
    } else if (!SWIG_GetPtr(s,&ptr,"_char_p")) {
      type = "char";
    } else if (!SWIG_GetPtr(s,&ptr,"_char_pp")) {
      type = "char *";
    } else {
      type = "unknown";
    }
  }

  if (!ptr) {
    PyErr_SetString(PyExc_TypeError,"Unable to set NULL pointer.");
    return NULL;
  }
  
  /* Now we have a datatype.  Try to figure out what to do about it */
  if (strcmp(type,"int") == 0) {
    *(((int *) ptr)+index) = (int) PyInt_AsLong(_PYVALUE);
  } else if (strcmp(type,"double") == 0) {
    *(((double *) ptr)+index) = (double) PyFloat_AsDouble(_PYVALUE);
  } else if (strcmp(type,"short") == 0) {
    *(((short *) ptr)+index) = (short) PyInt_AsLong(_PYVALUE);
  } else if (strcmp(type,"long") == 0) {
    *(((long *) ptr)+index) = (long) PyInt_AsLong(_PYVALUE);
  } else if (strcmp(type,"float") == 0) {
    *(((float *) ptr)+index) = (float) PyFloat_AsDouble(_PYVALUE);
  } else if (strcmp(type,"char") == 0) {
    char *c = PyString_AsString(_PYVALUE);
    strcpy(((char *) ptr)+index, c);
  } else if (strcmp(type,"char *") == 0) {
    char *c = PyString_AsString(_PYVALUE);
    char **ca = (char **) ptr;
    if (ca[index]) free(ca[index]);
    if (strcmp(c,"NULL") == 0) {
      ca[index] = 0;
    } else {
      ca[index] = (char *) malloc(strlen(c)+1);
      strcpy(ca[index],c);
    }
  } else {
    PyErr_SetString(PyExc_TypeError,"Unable to set unsupported datatype.");
    return NULL;
  }
  Py_INCREF(Py_None);
  return Py_None;
}


/*------------------------------------------------------------------
  ptradd(ptr,offset)

  Adds a value to an existing pointer value.  Will do a type-dependent
  add for basic datatypes.  For other datatypes, will do a byte-add.
  ------------------------------------------------------------------ */

static PyObject *captradd(PyObject *_PTRVALUE, int offset) {

  char *r,*s;
  void *ptr,*junk;
  PyObject *obj=NULL;
  char *type;

  /* Check to see what kind of object _PTRVALUE is */
  
  if (PyString_Check(_PTRVALUE)) {
    /* Have a potential pointer value now.  Try to strip out the value */
    s = PyString_AsString(_PTRVALUE);

    /* Try to handle a few common datatypes first */

    if (!SWIG_GetPtr(s,&ptr,"_int_p")) {
      ptr = (void *) (((int *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,"_double_p")) {
      ptr = (void *) (((double *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,"_short_p")) {
      ptr = (void *) (((short *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,"_long_p")) {
      ptr = (void *) (((long *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,"_float_p")) {
      ptr = (void *) (((float *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,"_char_p")) {
      ptr = (void *) (((char *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,0)) {
      ptr = (void *) (((char *) ptr) + offset);
    } else {
      PyErr_SetString(PyExc_TypeError,"Type error in ptradd. Argument is not a valid pointer value.");
      return NULL;
    }
    type = SWIG_GetPtr(s,&junk,"INVALID POINTER");
    r = (char *) malloc(strlen(type)+20);
    if (ptr) {
      SWIG_MakePtr(r,ptr,type);
    } else {
      sprintf(r,"_0%s",type);
    }
    obj = PyString_FromString(r);
    free(r);
  }
  return obj;
}

/*------------------------------------------------------------------
  ptrmap(type1,type2)

  Allows a mapping between type1 and type2. (Like a typedef)
  ------------------------------------------------------------------ */

static void captrmap(char *type1, char *type2) {

  char *typestr1,*typestr2,*c,*r;

  /* Produce a "mangled" version of the type string.  */

  typestr1 = (char *) malloc(strlen(type1)+2);
  
  /* Go through and munge the typestring */
  
  r = typestr1;
  *(r++) = '_';
  c = type1;
  while (*c) {
    if (!isspace(*c)) {
      if ((*c == '*') || (*c == '&')) {
	*(r++) = 'p';
      }
      else *(r++) = *c;
    } else {
      *(r++) = '_';
    }
    c++;
  }
  *(r++) = 0;
  
  typestr2 = (char *) malloc(strlen(type2)+2);

  /* Go through and munge the typestring */
  
  r = typestr2;
  *(r++) = '_';
  c = type2;
  while (*c) {
    if (!isspace(*c)) {
      if ((*c == '*') || (*c == '&')) {
	*(r++) = 'p';
      }
      else *(r++) = *c;
    } else {
      *(r++) = '_';
    }
    c++;
  }
  *(r++) = 0;
  SWIG_RegisterMapping(typestr1,typestr2,0);
  SWIG_RegisterMapping(typestr2,typestr1,0);
}

/*------------------------------------------------------------------
  ptrfree(ptr)

  Destroys a pointer value
  ------------------------------------------------------------------ */

PyObject *captrfree(PyObject *_PTRVALUE) {
  void *ptr, *junk;
  char *s;

  if (!PyString_Check(_PTRVALUE)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrfree. Argument is not a valid pointer value.");
    return NULL;
  }
  s = PyString_AsString(_PTRVALUE);
  if (SWIG_GetPtr(s,&ptr,0)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrfree. Argument is not a valid pointer value.");
    return NULL;
  }

  /* Check to see if this pointer is a char ** */
  if (!SWIG_GetPtr(s,&junk,"_char_pp")) {
    char **c = (char **) ptr;
    if (c) {
      int i = 0;
      while (c[i]) {
	free(c[i]);
	i++;
      }
    }
  } 
  if (ptr)
    free((char *) ptr);

  Py_INCREF(Py_None);
  return Py_None;
}


#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_version(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    
    if(!PyArg_ParseTuple(args,(char *)":version")) goto fail;
    caVersion();
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_chid(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_chid")) goto fail;
    result = (chid *)new_chid();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_chid, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_free_chid(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid *arg1 = (chid *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:free_chid",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    free_chid(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_evid(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    evid *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_evid")) goto fail;
    result = (evid *)new_evid();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_evid, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_free_evid(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    evid *arg1 = (evid *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:free_evid",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_evid,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    free_evid(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_clear_channel(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    int result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:clear_channel",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (int)close_channel(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_clear_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    evid arg1 ;
    int result;
    evid *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:clear_event",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_evid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (int)close_event(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_field_type(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    int result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:field_type",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (int)ca_field_type_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_element_count(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    unsigned int result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:element_count",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (unsigned int)ca_element_count_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_name(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    char *result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:name",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (char *)ca_name_macro(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_puser(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    void *result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:puser",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (void *)ca_puser_macro(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_state(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    int result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:state",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (int)ca_state_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_message(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    char *result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:message",&arg1)) goto fail;
    result = (char *)ca_message_macro(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_host_name(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    char *result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:host_name",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (char *)ca_host_name_macro(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_read_access(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    int result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:read_access",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (int)ca_read_access_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_write_access(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    int result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:write_access",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (int)ca_write_access_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbr_size_n(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    int arg2 ;
    unsigned int result;
    
    if(!PyArg_ParseTuple(args,(char *)"li:dbr_size_n",&arg1,&arg2)) goto fail;
    result = (unsigned int)dbr_size_n_macro(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbr_size(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    unsigned int result;
    
    if(!PyArg_ParseTuple(args,(char *)"l:dbr_size",&arg1)) goto fail;
    result = (unsigned int)dbr_size_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbr_value_size(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    unsigned int result;
    
    if(!PyArg_ParseTuple(args,(char *)"l:dbr_value_size",&arg1)) goto fail;
    result = (unsigned int)dbr_value_size_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_valid_db_req(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:valid_db_req",&arg1)) goto fail;
    result = (int)valid_db_req_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_invalid_db_req(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:invalid_db_req",&arg1)) goto fail;
    result = (int)invalid_db_req_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbr_text(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    char *result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbr_text",&arg1)) goto fail;
    result = (char *)dbr_text_macro(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbf_text(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    char *result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbf_text",&arg1)) goto fail;
    result = (char *)dbf_text_macro(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbf_type_to_DBR(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbf_type_to_DBR",&arg1)) goto fail;
    result = (int)dbf_type_to_DBR_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbf_type_to_DBR_STS(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbf_type_to_DBR_STS",&arg1)) goto fail;
    result = (int)dbf_type_to_DBR_STS_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbf_type_to_DBR_TIME(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbf_type_to_DBR_TIME",&arg1)) goto fail;
    result = (int)dbf_type_to_DBR_TIME_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbf_type_to_DBR_GR(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbf_type_to_DBR_GR",&arg1)) goto fail;
    result = (int)dbf_type_to_DBR_GR_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbf_type_to_DBR_CTRL(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbf_type_to_DBR_CTRL",&arg1)) goto fail;
    result = (int)dbf_type_to_DBR_CTRL_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbr_type_is_valid(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbr_type_is_valid",&arg1)) goto fail;
    result = (int)dbr_type_is_valid_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbr_type_is_plain(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbr_type_is_plain",&arg1)) goto fail;
    result = (int)dbr_type_is_plain_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbr_type_is_STS(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbr_type_is_STS",&arg1)) goto fail;
    result = (int)dbr_type_is_STS_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbr_type_is_TIME(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbr_type_is_TIME",&arg1)) goto fail;
    result = (int)dbr_type_is_TIME_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbr_type_is_GR(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbr_type_is_GR",&arg1)) goto fail;
    result = (int)dbr_type_is_GR_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_dbr_type_is_CTRL(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:dbr_type_is_CTRL",&arg1)) goto fail;
    result = (int)dbr_type_is_CTRL_macro(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_alarmSeverityString(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    char *result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:alarmSeverityString",&arg1)) goto fail;
    result = (char *)alarmSeverityString_macro(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_alarmStatusString(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    char *result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:alarmStatusString",&arg1)) goto fail;
    result = (char *)alarmStatusString_macro(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_fdmgr_start(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    
    if(!PyArg_ParseTuple(args,(char *)":fdmgr_start")) goto fail;
    fdmgr_start();
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_fdmgr_pend(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    
    if(!PyArg_ParseTuple(args,(char *)":fdmgr_pend")) goto fail;
    fdmgr_pend();
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_task_initialize(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)":task_initialize")) goto fail;
    result = (int)ca_task_initialize();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_task_exit(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)":task_exit")) goto fail;
    result = (int)ca_task_exit();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_search_and_connect(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    chid *arg2 = (chid *) 0 ;
    void *arg3 = (void *) 0 ;
    void *arg4 = (void *) 0 ;
    int result;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"sOOO:search_and_connect",&arg1,&obj1,&obj2,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        arg3 = connectCallback;
    }
    {
        arg4 = obj3;
        Py_INCREF(obj3);
    }
    result = (int)ca_search_and_connect(arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_search(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    chid *arg2 = (chid *) 0 ;
    int result;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"sO:search",&arg1,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_search(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_array_put(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    unsigned long arg2 ;
    chid arg3 ;
    void *arg4 = (void *) 0 ;
    int result;
    chid *argp3 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"lOOO:array_put",&arg1,&obj1,&obj2,&obj3)) goto fail;
    arg2 = (unsigned long) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &argp3, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg3 = *argp3; 
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_array_put(arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_put(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    chid arg2 ;
    void *arg3 = (void *) 0 ;
    int result;
    chid *argp2 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"lOO:put",&arg1,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_put(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_bput(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    char *arg2 ;
    int result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:bput",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (int)ca_bput(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_rput(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    dbr_float_t *arg2 = (dbr_float_t *) 0 ;
    int result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:rput",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_dbr_float_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_rput(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_array_put_callback(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    unsigned long arg2 ;
    chid arg3 ;
    void *arg4 = (void *) 0 ;
    void *arg5 = (void *) 0 ;
    void *arg6 = (void *) 0 ;
    int result;
    chid *argp3 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    PyObject * obj5 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"lOOOOO:array_put_callback",&arg1,&obj1,&obj2,&obj3,&obj4,&obj5)) goto fail;
    arg2 = (unsigned long) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &argp3, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg3 = *argp3; 
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        arg5 = putCallback;
    }
    {
        arg6 = obj5;
        Py_INCREF(obj5);
    }
    result = (int)ca_array_put_callback(arg1,arg2,arg3,arg4,arg5,arg6);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_put_callback(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    chid arg2 ;
    void *arg3 = (void *) 0 ;
    void *arg4 = (void *) 0 ;
    void *arg5 = (void *) 0 ;
    int result;
    chid *argp2 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"lOOOO:put_callback",&arg1,&obj1,&obj2,&obj3,&obj4)) goto fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        arg4 = putCallback;
    }
    {
        arg5 = obj4;
        Py_INCREF(obj4);
    }
    result = (int)ca_put_callback(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_array_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    unsigned long arg2 ;
    chid arg3 ;
    void *arg4 = (void *) 0 ;
    int result;
    chid *argp3 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"lOOO:array_get",&arg1,&obj1,&obj2,&obj3)) goto fail;
    arg2 = (unsigned long) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &argp3, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg3 = *argp3; 
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_array_get(arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    chid arg2 ;
    void *arg3 = (void *) 0 ;
    int result;
    chid *argp2 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"lOO:get",&arg1,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_get(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_bget(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    void *arg2 = (void *) 0 ;
    int result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:bget",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_bget(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_rget(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chid arg1 ;
    dbr_float_t *arg2 = (dbr_float_t *) 0 ;
    int result;
    chid *argp1 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:rget",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_dbr_float_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_rget(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_get_callback(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    chid arg2 ;
    void *arg3 = (void *) 0 ;
    void *arg4 = (void *) 0 ;
    int result;
    chid *argp2 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"lOOO:get_callback",&arg1,&obj1,&obj2,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    {
        arg3 = getCallback;
    }
    {
        arg4 = obj3;
        Py_INCREF(obj3);
    }
    result = (int)ca_get_callback(arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_array_get_callback(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    unsigned long arg2 ;
    chid arg3 ;
    void *arg4 = (void *) 0 ;
    void *arg5 = (void *) 0 ;
    int result;
    chid *argp3 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"lOOOO:array_get_callback",&arg1,&obj1,&obj2,&obj3,&obj4)) goto fail;
    arg2 = (unsigned long) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &argp3, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg3 = *argp3; 
    {
        arg4 = getCallback;
    }
    {
        arg5 = obj4;
        Py_INCREF(obj4);
    }
    result = (int)ca_array_get_callback(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_add_masked_array_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    unsigned long arg2 ;
    chid arg3 ;
    void *arg4 = (void *) 0 ;
    void *arg5 = (void *) 0 ;
    double arg6 ;
    double arg7 ;
    double arg8 ;
    evid *arg9 = (evid *) 0 ;
    unsigned long arg10 ;
    int result;
    chid *argp3 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    PyObject * obj5 = 0 ;
    PyObject * obj6 = 0 ;
    PyObject * obj7 = 0 ;
    PyObject * obj8 = 0 ;
    PyObject * obj9 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"lOOOOOOOOO:add_masked_array_event",&arg1,&obj1,&obj2,&obj3,&obj4,&obj5,&obj6,&obj7,&obj8,&obj9)) goto fail;
    arg2 = (unsigned long) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &argp3, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg3 = *argp3; 
    {
        arg4 = eventCallback;
    }
    {
        arg5 = obj4;
        Py_INCREF(obj4);
    }
    {
        arg6 = 0.0;
    }
    {
        arg7 = 0.0;
    }
    {
        arg8 = 0.0;
    }
    if ((SWIG_ConvertPtr(obj8,(void **) &arg9, SWIGTYPE_p_evid,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg10 = (unsigned long) PyInt_AsLong(obj9);
    if (PyErr_Occurred()) SWIG_fail;
    result = (int)ca_add_masked_array_event(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_add_array_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    unsigned long arg2 ;
    chid arg3 ;
    void *arg4 = (void *) 0 ;
    void *arg5 = (void *) 0 ;
    double arg6 ;
    double arg7 ;
    double arg8 ;
    evid *arg9 = (evid *) 0 ;
    int result;
    chid *argp3 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    PyObject * obj5 = 0 ;
    PyObject * obj6 = 0 ;
    PyObject * obj7 = 0 ;
    PyObject * obj8 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"lOOOOOOOO:add_array_event",&arg1,&obj1,&obj2,&obj3,&obj4,&obj5,&obj6,&obj7,&obj8)) goto fail;
    arg2 = (unsigned long) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &argp3, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg3 = *argp3; 
    {
        arg4 = eventCallback;
    }
    {
        arg5 = obj4;
        Py_INCREF(obj4);
    }
    {
        arg6 = 0.0;
    }
    {
        arg7 = 0.0;
    }
    {
        arg8 = 0.0;
    }
    if ((SWIG_ConvertPtr(obj8,(void **) &arg9, SWIGTYPE_p_evid,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_add_array_event(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_add_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    chtype arg1 ;
    chid arg2 ;
    void *arg3 = (void *) 0 ;
    void *arg4 = (void *) 0 ;
    evid *arg5 = (evid *) 0 ;
    int result;
    chid *argp2 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"lOOOO:add_event",&arg1,&obj1,&obj2,&obj3,&obj4)) goto fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    {
        arg3 = eventCallback;
    }
    {
        arg4 = obj3;
        Py_INCREF(obj3);
    }
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, SWIGTYPE_p_evid,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_add_event(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_pend_io(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"d:pend_io",&arg1)) goto fail;
    result = (int)ca_pend_io(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_test_io(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)":test_io")) goto fail;
    result = (int)ca_test_io();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_pend_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"d:pend_event",&arg1)) goto fail;
    result = (int)ca_pend_event(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_poll(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)":poll")) goto fail;
    result = (int)ca_poll();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_flush_io(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)":flush_io")) goto fail;
    result = (int)ca_flush_io();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_signal(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    long arg1 ;
    char *arg2 ;
    
    if(!PyArg_ParseTuple(args,(char *)"ls:signal",&arg1,&arg2)) goto fail;
    ca_signal(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SEVCHK(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    long arg1 ;
    char *arg2 ;
    
    if(!PyArg_ParseTuple(args,(char *)"ls:SEVCHK",&arg1,&arg2)) goto fail;
    SEVCHK(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_test_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct event_handler_args arg1 ;
    struct event_handler_args *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:test_event",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_event_handler_args,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    ca_test_event(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_add_fd_registration(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    void *arg1 = (void *) 0 ;
    void *arg2 = (void *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:add_fd_registration",&obj0,&obj1)) goto fail;
    {
        arg1 = getCallback;
    }
    {
        arg2 = obj1;
        Py_INCREF(obj1);
    }
    result = (int)ca_add_fd_registration(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_modify_user_name(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"s:modify_user_name",&arg1)) goto fail;
    result = (int)ca_modify_user_name(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_modify_host_name(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"s:modify_host_name",&arg1)) goto fail;
    result = (int)ca_modify_host_name(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_sg_create(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CA_SYNC_GID *arg1 = (CA_SYNC_GID *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:sg_create",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_CA_SYNC_GID,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_sg_create(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_sg_delete(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CA_SYNC_GID arg1 ;
    int result;
    CA_SYNC_GID *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:sg_delete",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_CA_SYNC_GID,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (int)ca_sg_delete(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_sg_block(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CA_SYNC_GID arg1 ;
    double arg2 ;
    int result;
    CA_SYNC_GID *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:sg_block",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_CA_SYNC_GID,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (int)ca_sg_block(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_sg_test(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CA_SYNC_GID arg1 ;
    int result;
    CA_SYNC_GID *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:sg_test",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_CA_SYNC_GID,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (int)ca_sg_test(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_sg_reset(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CA_SYNC_GID arg1 ;
    int result;
    CA_SYNC_GID *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:sg_reset",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_CA_SYNC_GID,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (int)ca_sg_reset(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_sg_put(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CA_SYNC_GID arg1 ;
    chtype arg2 ;
    unsigned long arg3 ;
    chid arg4 ;
    void *arg5 = (void *) 0 ;
    int result;
    CA_SYNC_GID *argp1 ;
    chid *argp4 ;
    PyObject * obj0 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OlOOO:sg_put",&obj0,&arg2,&obj2,&obj3,&obj4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_CA_SYNC_GID,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    arg3 = (unsigned long) PyInt_AsLong(obj2);
    if (PyErr_Occurred()) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &argp4, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg4 = *argp4; 
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_sg_array_put(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_sg_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    CA_SYNC_GID arg1 ;
    chtype arg2 ;
    unsigned long arg3 ;
    chid arg4 ;
    void *arg5 = (void *) 0 ;
    int result;
    CA_SYNC_GID *argp1 ;
    chid *argp4 ;
    PyObject * obj0 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OlOOO:sg_get",&obj0,&arg2,&obj2,&obj3,&obj4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_CA_SYNC_GID,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    arg3 = (unsigned long) PyInt_AsLong(obj2);
    if (PyErr_Occurred()) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &argp4, SWIGTYPE_p_chid,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg4 = *argp4; 
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)ca_sg_array_get(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_captrcast(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PyObject *arg1 = (PyObject *) 0 ;
    char *arg2 ;
    PyObject *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:captrcast",&obj0,&arg2)) goto fail;
    {
        arg1 = obj0;
    }
    result = (PyObject *)captrcast(arg1,arg2);
    
    {
        resultobj = result;
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_captrvalue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PyObject *arg1 = (PyObject *) 0 ;
    int arg2 = (int) 0 ;
    char *arg3 = (char *) 0 ;
    PyObject *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O|is:captrvalue",&obj0,&arg2,&arg3)) goto fail;
    {
        arg1 = obj0;
    }
    result = (PyObject *)captrvalue(arg1,arg2,arg3);
    
    {
        resultobj = result;
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_captrset(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PyObject *arg1 = (PyObject *) 0 ;
    PyObject *arg2 = (PyObject *) 0 ;
    int arg3 = (int) 0 ;
    char *arg4 = (char *) 0 ;
    PyObject *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO|is:captrset",&obj0,&obj1,&arg3,&arg4)) goto fail;
    {
        arg1 = obj0;
    }
    {
        arg2 = obj1;
    }
    result = (PyObject *)captrset(arg1,arg2,arg3,arg4);
    
    {
        resultobj = result;
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_captrcreate(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    PyObject *arg2 = (PyObject *) 0 ;
    int arg3 = (int) 1 ;
    PyObject *result;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"s|Oi:captrcreate",&arg1,&obj1,&arg3)) goto fail;
    if (obj1) {
        {
            arg2 = obj1;
        }
    }
    result = (PyObject *)captrcreate(arg1,arg2,arg3);
    
    {
        resultobj = result;
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_captrfree(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PyObject *arg1 = (PyObject *) 0 ;
    PyObject *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:captrfree",&obj0)) goto fail;
    {
        arg1 = obj0;
    }
    result = (PyObject *)captrfree(arg1);
    
    {
        resultobj = result;
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_captradd(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PyObject *arg1 = (PyObject *) 0 ;
    int arg2 ;
    PyObject *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:captradd",&obj0,&arg2)) goto fail;
    {
        arg1 = obj0;
    }
    result = (PyObject *)captradd(arg1,arg2);
    
    {
        resultobj = result;
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_captrmap(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    char *arg2 ;
    
    if(!PyArg_ParseTuple(args,(char *)"ss:captrmap",&arg1,&arg2)) goto fail;
    captrmap(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyMethodDef SwigMethods[] = {
	 { (char *)"version", _wrap_version, METH_VARARGS },
	 { (char *)"new_chid", _wrap_new_chid, METH_VARARGS },
	 { (char *)"free_chid", _wrap_free_chid, METH_VARARGS },
	 { (char *)"new_evid", _wrap_new_evid, METH_VARARGS },
	 { (char *)"free_evid", _wrap_free_evid, METH_VARARGS },
	 { (char *)"clear_channel", _wrap_clear_channel, METH_VARARGS },
	 { (char *)"clear_event", _wrap_clear_event, METH_VARARGS },
	 { (char *)"field_type", _wrap_field_type, METH_VARARGS },
	 { (char *)"element_count", _wrap_element_count, METH_VARARGS },
	 { (char *)"name", _wrap_name, METH_VARARGS },
	 { (char *)"puser", _wrap_puser, METH_VARARGS },
	 { (char *)"state", _wrap_state, METH_VARARGS },
	 { (char *)"message", _wrap_message, METH_VARARGS },
	 { (char *)"host_name", _wrap_host_name, METH_VARARGS },
	 { (char *)"read_access", _wrap_read_access, METH_VARARGS },
	 { (char *)"write_access", _wrap_write_access, METH_VARARGS },
	 { (char *)"dbr_size_n", _wrap_dbr_size_n, METH_VARARGS },
	 { (char *)"dbr_size", _wrap_dbr_size, METH_VARARGS },
	 { (char *)"dbr_value_size", _wrap_dbr_value_size, METH_VARARGS },
	 { (char *)"valid_db_req", _wrap_valid_db_req, METH_VARARGS },
	 { (char *)"invalid_db_req", _wrap_invalid_db_req, METH_VARARGS },
	 { (char *)"dbr_text", _wrap_dbr_text, METH_VARARGS },
	 { (char *)"dbf_text", _wrap_dbf_text, METH_VARARGS },
	 { (char *)"dbf_type_to_DBR", _wrap_dbf_type_to_DBR, METH_VARARGS },
	 { (char *)"dbf_type_to_DBR_STS", _wrap_dbf_type_to_DBR_STS, METH_VARARGS },
	 { (char *)"dbf_type_to_DBR_TIME", _wrap_dbf_type_to_DBR_TIME, METH_VARARGS },
	 { (char *)"dbf_type_to_DBR_GR", _wrap_dbf_type_to_DBR_GR, METH_VARARGS },
	 { (char *)"dbf_type_to_DBR_CTRL", _wrap_dbf_type_to_DBR_CTRL, METH_VARARGS },
	 { (char *)"dbr_type_is_valid", _wrap_dbr_type_is_valid, METH_VARARGS },
	 { (char *)"dbr_type_is_plain", _wrap_dbr_type_is_plain, METH_VARARGS },
	 { (char *)"dbr_type_is_STS", _wrap_dbr_type_is_STS, METH_VARARGS },
	 { (char *)"dbr_type_is_TIME", _wrap_dbr_type_is_TIME, METH_VARARGS },
	 { (char *)"dbr_type_is_GR", _wrap_dbr_type_is_GR, METH_VARARGS },
	 { (char *)"dbr_type_is_CTRL", _wrap_dbr_type_is_CTRL, METH_VARARGS },
	 { (char *)"alarmSeverityString", _wrap_alarmSeverityString, METH_VARARGS },
	 { (char *)"alarmStatusString", _wrap_alarmStatusString, METH_VARARGS },
	 { (char *)"fdmgr_start", _wrap_fdmgr_start, METH_VARARGS },
	 { (char *)"fdmgr_pend", _wrap_fdmgr_pend, METH_VARARGS },
	 { (char *)"task_initialize", _wrap_task_initialize, METH_VARARGS },
	 { (char *)"task_exit", _wrap_task_exit, METH_VARARGS },
	 { (char *)"search_and_connect", _wrap_search_and_connect, METH_VARARGS },
	 { (char *)"search", _wrap_search, METH_VARARGS },
	 { (char *)"array_put", _wrap_array_put, METH_VARARGS },
	 { (char *)"put", _wrap_put, METH_VARARGS },
	 { (char *)"bput", _wrap_bput, METH_VARARGS },
	 { (char *)"rput", _wrap_rput, METH_VARARGS },
	 { (char *)"array_put_callback", _wrap_array_put_callback, METH_VARARGS },
	 { (char *)"put_callback", _wrap_put_callback, METH_VARARGS },
	 { (char *)"array_get", _wrap_array_get, METH_VARARGS },
	 { (char *)"get", _wrap_get, METH_VARARGS },
	 { (char *)"bget", _wrap_bget, METH_VARARGS },
	 { (char *)"rget", _wrap_rget, METH_VARARGS },
	 { (char *)"get_callback", _wrap_get_callback, METH_VARARGS },
	 { (char *)"array_get_callback", _wrap_array_get_callback, METH_VARARGS },
	 { (char *)"add_masked_array_event", _wrap_add_masked_array_event, METH_VARARGS },
	 { (char *)"add_array_event", _wrap_add_array_event, METH_VARARGS },
	 { (char *)"add_event", _wrap_add_event, METH_VARARGS },
	 { (char *)"pend_io", _wrap_pend_io, METH_VARARGS },
	 { (char *)"test_io", _wrap_test_io, METH_VARARGS },
	 { (char *)"pend_event", _wrap_pend_event, METH_VARARGS },
	 { (char *)"poll", _wrap_poll, METH_VARARGS },
	 { (char *)"flush_io", _wrap_flush_io, METH_VARARGS },
	 { (char *)"signal", _wrap_signal, METH_VARARGS },
	 { (char *)"SEVCHK", _wrap_SEVCHK, METH_VARARGS },
	 { (char *)"test_event", _wrap_test_event, METH_VARARGS },
	 { (char *)"add_fd_registration", _wrap_add_fd_registration, METH_VARARGS },
	 { (char *)"modify_user_name", _wrap_modify_user_name, METH_VARARGS },
	 { (char *)"modify_host_name", _wrap_modify_host_name, METH_VARARGS },
	 { (char *)"sg_create", _wrap_sg_create, METH_VARARGS },
	 { (char *)"sg_delete", _wrap_sg_delete, METH_VARARGS },
	 { (char *)"sg_block", _wrap_sg_block, METH_VARARGS },
	 { (char *)"sg_test", _wrap_sg_test, METH_VARARGS },
	 { (char *)"sg_reset", _wrap_sg_reset, METH_VARARGS },
	 { (char *)"sg_put", _wrap_sg_put, METH_VARARGS },
	 { (char *)"sg_get", _wrap_sg_get, METH_VARARGS },
	 { (char *)"captrcast", _wrap_captrcast, METH_VARARGS },
	 { (char *)"captrvalue", _wrap_captrvalue, METH_VARARGS },
	 { (char *)"captrset", _wrap_captrset, METH_VARARGS },
	 { (char *)"captrcreate", _wrap_captrcreate, METH_VARARGS },
	 { (char *)"captrfree", _wrap_captrfree, METH_VARARGS },
	 { (char *)"captradd", _wrap_captradd, METH_VARARGS },
	 { (char *)"captrmap", _wrap_captrmap, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_chid[] = {{"_p_chid", 0, "chid *", 0},{"_p_chid"},{0}};
static swig_type_info _swigt__p_event_handler_args[] = {{"_p_event_handler_args", 0, "struct event_handler_args *", 0},{"_p_event_handler_args"},{0}};
static swig_type_info _swigt__p_evid[] = {{"_p_evid", 0, "evid *", 0},{"_p_evid"},{0}};
static swig_type_info _swigt__p_void[] = {{"_p_void", 0, "void *", 0},{"_p_void"},{0}};
static swig_type_info _swigt__p_CA_SYNC_GID[] = {{"_p_CA_SYNC_GID", 0, "CA_SYNC_GID *", 0},{"_p_CA_SYNC_GID"},{0}};
static swig_type_info _swigt__p_dbr_float_t[] = {{"_p_dbr_float_t", 0, "dbr_float_t *", 0},{"_p_dbr_float_t"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_chid, 
_swigt__p_event_handler_args, 
_swigt__p_evid, 
_swigt__p_void, 
_swigt__p_CA_SYNC_GID, 
_swigt__p_dbr_float_t, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
    
    /* Field types */
    /* Native types, DBF_XXXX */
    PyDict_SetItemString(d, "DBF_STRING", PyInt_FromLong((long) DBF_STRING));
    PyDict_SetItemString(d, "DBF_SHORT", PyInt_FromLong((long) DBF_SHORT));
    PyDict_SetItemString(d, "DBF_INT", PyInt_FromLong((long) DBF_INT));
    PyDict_SetItemString(d, "DBF_FLOAT", PyInt_FromLong((long) DBF_FLOAT));
    PyDict_SetItemString(d, "DBF_ENUM", PyInt_FromLong((long) DBF_ENUM));
    PyDict_SetItemString(d, "DBF_CHAR", PyInt_FromLong((long) DBF_CHAR));
    PyDict_SetItemString(d, "DBF_LONG", PyInt_FromLong((long) DBF_LONG));
    PyDict_SetItemString(d, "DBF_DOUBLE", PyInt_FromLong((long) DBF_DOUBLE));
    
    /* Request types, DBR_XXXX */
    PyDict_SetItemString(d, "DBR_STRING", PyInt_FromLong((long) DBR_STRING));
    PyDict_SetItemString(d, "DBR_SHORT", PyInt_FromLong((long) DBR_SHORT));
    PyDict_SetItemString(d, "DBR_INT", PyInt_FromLong((long) DBR_INT));
    PyDict_SetItemString(d, "DBR_FLOAT", PyInt_FromLong((long) DBR_FLOAT));
    PyDict_SetItemString(d, "DBR_ENUM", PyInt_FromLong((long) DBR_ENUM));
    PyDict_SetItemString(d, "DBR_CHAR", PyInt_FromLong((long) DBR_CHAR));
    PyDict_SetItemString(d, "DBR_LONG", PyInt_FromLong((long) DBR_LONG));
    PyDict_SetItemString(d, "DBR_DOUBLE", PyInt_FromLong((long) DBR_DOUBLE));
    
    /* Status request types, DBR_STS_XXXX */
    PyDict_SetItemString(d, "DBR_STS_STRING", PyInt_FromLong((long) DBR_STS_STRING));
    PyDict_SetItemString(d, "DBR_STS_SHORT", PyInt_FromLong((long) DBR_STS_SHORT));
    PyDict_SetItemString(d, "DBR_STS_INT", PyInt_FromLong((long) DBR_STS_INT));
    PyDict_SetItemString(d, "DBR_STS_FLOAT", PyInt_FromLong((long) DBR_STS_FLOAT));
    PyDict_SetItemString(d, "DBR_STS_ENUM", PyInt_FromLong((long) DBR_STS_ENUM));
    PyDict_SetItemString(d, "DBR_STS_CHAR", PyInt_FromLong((long) DBR_STS_CHAR));
    PyDict_SetItemString(d, "DBR_STS_LONG", PyInt_FromLong((long) DBR_STS_LONG));
    PyDict_SetItemString(d, "DBR_STS_DOUBLE", PyInt_FromLong((long) DBR_STS_DOUBLE));
    
    /* Time request types, DBR_TIME_XXXX */
    PyDict_SetItemString(d, "DBR_TIME_STRING", PyInt_FromLong((long) DBR_TIME_STRING));
    PyDict_SetItemString(d, "DBR_TIME_SHORT", PyInt_FromLong((long) DBR_TIME_SHORT));
    PyDict_SetItemString(d, "DBR_TIME_INT", PyInt_FromLong((long) DBR_TIME_INT));
    PyDict_SetItemString(d, "DBR_TIME_FLOAT", PyInt_FromLong((long) DBR_TIME_FLOAT));
    PyDict_SetItemString(d, "DBR_TIME_ENUM", PyInt_FromLong((long) DBR_TIME_ENUM));
    PyDict_SetItemString(d, "DBR_TIME_CHAR", PyInt_FromLong((long) DBR_TIME_CHAR));
    PyDict_SetItemString(d, "DBR_TIME_LONG", PyInt_FromLong((long) DBR_TIME_LONG));
    PyDict_SetItemString(d, "DBR_TIME_DOUBLE", PyInt_FromLong((long) DBR_TIME_DOUBLE));
    
    /* Graphics request types, DBR_GR_XXXX */
    PyDict_SetItemString(d, "DBR_GR_STRING", PyInt_FromLong((long) DBR_GR_STRING));
    PyDict_SetItemString(d, "DBR_GR_SHORT", PyInt_FromLong((long) DBR_GR_SHORT));
    PyDict_SetItemString(d, "DBR_GR_INT", PyInt_FromLong((long) DBR_GR_INT));
    PyDict_SetItemString(d, "DBR_GR_FLOAT", PyInt_FromLong((long) DBR_GR_FLOAT));
    PyDict_SetItemString(d, "DBR_GR_ENUM", PyInt_FromLong((long) DBR_GR_ENUM));
    PyDict_SetItemString(d, "DBR_GR_CHAR", PyInt_FromLong((long) DBR_GR_CHAR));
    PyDict_SetItemString(d, "DBR_GR_LONG", PyInt_FromLong((long) DBR_GR_LONG));
    PyDict_SetItemString(d, "DBR_GR_DOUBLE", PyInt_FromLong((long) DBR_GR_DOUBLE));
    
    /* Control request types, DBR_CTRL_XXXX */
    PyDict_SetItemString(d, "DBR_CTRL_STRING", PyInt_FromLong((long) DBR_CTRL_STRING));
    PyDict_SetItemString(d, "DBR_CTRL_SHORT", PyInt_FromLong((long) DBR_CTRL_SHORT));
    PyDict_SetItemString(d, "DBR_CTRL_INT", PyInt_FromLong((long) DBR_CTRL_INT));
    PyDict_SetItemString(d, "DBR_CTRL_FLOAT", PyInt_FromLong((long) DBR_CTRL_FLOAT));
    PyDict_SetItemString(d, "DBR_CTRL_ENUM", PyInt_FromLong((long) DBR_CTRL_ENUM));
    PyDict_SetItemString(d, "DBR_CTRL_CHAR", PyInt_FromLong((long) DBR_CTRL_CHAR));
    PyDict_SetItemString(d, "DBR_CTRL_LONG", PyInt_FromLong((long) DBR_CTRL_LONG));
    PyDict_SetItemString(d, "DBR_CTRL_DOUBLE", PyInt_FromLong((long) DBR_CTRL_DOUBLE));
    
    /* Miscellaneous request types */
    PyDict_SetItemString(d, "DBR_PUT_ACKT", PyInt_FromLong((long) DBR_PUT_ACKT));
    PyDict_SetItemString(d, "DBR_PUT_ACKS", PyInt_FromLong((long) DBR_PUT_ACKS));
    PyDict_SetItemString(d, "DBR_STSACK_STRING", PyInt_FromLong((long) DBR_STSACK_STRING));
    PyDict_SetItemString(d, "DBR_STSACK_STRING", PyInt_FromLong((long) DBR_STSACK_STRING));
    PyDict_SetItemString(d, "LAST_BUFFER_TYPE", PyInt_FromLong((long) LAST_BUFFER_TYPE));
    PyDict_SetItemString(d, "DBR_CTRL_CHAR", PyInt_FromLong((long) DBR_CTRL_CHAR));
    PyDict_SetItemString(d, "DBR_CTRL_LONG", PyInt_FromLong((long) DBR_CTRL_LONG));
    PyDict_SetItemString(d, "DBR_CTRL_DOUBLE", PyInt_FromLong((long) DBR_CTRL_DOUBLE));
    
    /* Return Codes, from caerr.h */
    PyDict_SetItemString(d, "ECA_NORMAL", PyInt_FromLong((long) ECA_NORMAL));
    PyDict_SetItemString(d, "ECA_MAXIOC", PyInt_FromLong((long) ECA_MAXIOC));
    PyDict_SetItemString(d, "ECA_UKNHOST", PyInt_FromLong((long) ECA_UKNHOST));
    PyDict_SetItemString(d, "ECA_UKNSERV", PyInt_FromLong((long) ECA_UKNSERV));
    PyDict_SetItemString(d, "ECA_SOCK", PyInt_FromLong((long) ECA_SOCK));
    PyDict_SetItemString(d, "ECA_CONN", PyInt_FromLong((long) ECA_CONN));
    PyDict_SetItemString(d, "ECA_ALLOCMEM", PyInt_FromLong((long) ECA_ALLOCMEM));
    PyDict_SetItemString(d, "ECA_UKNCHAN", PyInt_FromLong((long) ECA_UKNCHAN));
    PyDict_SetItemString(d, "ECA_UKNFIELD", PyInt_FromLong((long) ECA_UKNFIELD));
    PyDict_SetItemString(d, "ECA_TIMEOUT", PyInt_FromLong((long) ECA_TIMEOUT));
    PyDict_SetItemString(d, "ECA_TOLARGE", PyInt_FromLong((long) ECA_TOLARGE));
    PyDict_SetItemString(d, "ECA_NOSUPPORT", PyInt_FromLong((long) ECA_NOSUPPORT));
    PyDict_SetItemString(d, "ECA_STRTOBIG", PyInt_FromLong((long) ECA_STRTOBIG));
    PyDict_SetItemString(d, "ECA_DISCONNCHID", PyInt_FromLong((long) ECA_DISCONNCHID));
    PyDict_SetItemString(d, "ECA_BADTYPE", PyInt_FromLong((long) ECA_BADTYPE));
    PyDict_SetItemString(d, "ECA_CHIDNOTFND", PyInt_FromLong((long) ECA_CHIDNOTFND));
    PyDict_SetItemString(d, "ECA_CHIDRETRY", PyInt_FromLong((long) ECA_CHIDRETRY));
    PyDict_SetItemString(d, "ECA_INTERNAL", PyInt_FromLong((long) ECA_INTERNAL));
    PyDict_SetItemString(d, "ECA_DBLCLFAIL", PyInt_FromLong((long) ECA_DBLCLFAIL));
    PyDict_SetItemString(d, "ECA_GETFAIL", PyInt_FromLong((long) ECA_GETFAIL));
    PyDict_SetItemString(d, "ECA_PUTFAIL", PyInt_FromLong((long) ECA_PUTFAIL));
    PyDict_SetItemString(d, "ECA_ADDFAIL", PyInt_FromLong((long) ECA_ADDFAIL));
    PyDict_SetItemString(d, "ECA_BADCOUNT", PyInt_FromLong((long) ECA_BADCOUNT));
    PyDict_SetItemString(d, "ECA_BADSTR", PyInt_FromLong((long) ECA_BADSTR));
    PyDict_SetItemString(d, "ECA_DISCONN", PyInt_FromLong((long) ECA_DISCONN));
    PyDict_SetItemString(d, "ECA_DBLCHNL", PyInt_FromLong((long) ECA_DBLCHNL));
    PyDict_SetItemString(d, "ECA_EVDISALLOW", PyInt_FromLong((long) ECA_EVDISALLOW));
    PyDict_SetItemString(d, "ECA_BUILDGET", PyInt_FromLong((long) ECA_BUILDGET));
    PyDict_SetItemString(d, "ECA_NEEDSFP", PyInt_FromLong((long) ECA_NEEDSFP));
    PyDict_SetItemString(d, "ECA_OVEVFAIL", PyInt_FromLong((long) ECA_OVEVFAIL));
    PyDict_SetItemString(d, "ECA_BADMONID", PyInt_FromLong((long) ECA_BADMONID));
    PyDict_SetItemString(d, "ECA_NEWADDR", PyInt_FromLong((long) ECA_NEWADDR));
    PyDict_SetItemString(d, "ECA_NEWCONN", PyInt_FromLong((long) ECA_NEWCONN));
    PyDict_SetItemString(d, "ECA_NOCACTX", PyInt_FromLong((long) ECA_NOCACTX));
    PyDict_SetItemString(d, "ECA_DEFUNCT", PyInt_FromLong((long) ECA_DEFUNCT));
    PyDict_SetItemString(d, "ECA_EMPTYSTR", PyInt_FromLong((long) ECA_EMPTYSTR));
    PyDict_SetItemString(d, "ECA_NOREPEATER", PyInt_FromLong((long) ECA_NOREPEATER));
    /*PyDict_SetItemString(d, "ECA_NOCHANMSG", PyInt_FromLong((long) ECA_NOCHANMSG)); */
    PyDict_SetItemString(d, "ECA_DLCKREST", PyInt_FromLong((long) ECA_DLCKREST));
    PyDict_SetItemString(d, "ECA_SERVBEHIND", PyInt_FromLong((long) ECA_SERVBEHIND));
    PyDict_SetItemString(d, "ECA_NOCAST", PyInt_FromLong((long) ECA_NOCAST));
    PyDict_SetItemString(d, "ECA_BADMASK", PyInt_FromLong((long) ECA_BADMASK));
    PyDict_SetItemString(d, "ECA_IODONE", PyInt_FromLong((long) ECA_IODONE));
    PyDict_SetItemString(d, "ECA_IOINPROGRESS", PyInt_FromLong((long) ECA_IOINPROGRESS));
    PyDict_SetItemString(d, "ECA_BADSYNCGRP", PyInt_FromLong((long) ECA_BADSYNCGRP));
    PyDict_SetItemString(d, "ECA_PUTCBINPROG", PyInt_FromLong((long) ECA_PUTCBINPROG));
    PyDict_SetItemString(d, "ECA_NORDACCESS", PyInt_FromLong((long) ECA_NORDACCESS));
    PyDict_SetItemString(d, "ECA_NOWTACCESS", PyInt_FromLong((long) ECA_NOWTACCESS));
    PyDict_SetItemString(d, "ECA_ANACHRONISM", PyInt_FromLong((long) ECA_ANACHRONISM));
    PyDict_SetItemString(d, "ECA_NOSEARCHADDR", PyInt_FromLong((long) ECA_NOSEARCHADDR));
    PyDict_SetItemString(d, "ECA_NOCONVERT", PyInt_FromLong((long) ECA_NOCONVERT));
    PyDict_SetItemString(d, "ECA_BADCHID", PyInt_FromLong((long) ECA_BADCHID));
    PyDict_SetItemString(d, "ECA_BADFUNCPTR", PyInt_FromLong((long) ECA_BADFUNCPTR));
    
    /* Connection Codes */
    PyDict_SetItemString(d, "CA_OP_CONN_UP", PyInt_FromLong((long) CA_OP_CONN_UP));
    PyDict_SetItemString(d, "CA_OP_CONN_DOWN", PyInt_FromLong((long) CA_OP_CONN_DOWN));
    PyDict_SetItemString(d, "cs_never_conn", PyInt_FromLong((long) cs_never_conn));
    PyDict_SetItemString(d, "cs_prev_conn", PyInt_FromLong((long) cs_prev_conn));
    PyDict_SetItemString(d, "cs_conn", PyInt_FromLong((long) cs_conn));
    PyDict_SetItemString(d, "cs_closed", PyInt_FromLong((long) cs_closed));
    
    /* Event Trigger Mask */
    PyDict_SetItemString(d, "DBE_VALUE", PyInt_FromLong((long) DBE_VALUE));
    PyDict_SetItemString(d, "DBE_LOG", PyInt_FromLong((long) DBE_LOG));
    PyDict_SetItemString(d, "DBE_ALARM", PyInt_FromLong((long) DBE_ALARM));
    
    
    if (PyErr_Occurred())
    Py_FatalError("initca: Error adding items to dictionary");
    
    /* ca_task_initialize() called when ca module is imported*/
    {
        int status;
        status = ca_task_initialize();
        
        if(ECA_NORMAL == status)
        /*printf("CA task initialized.\n")*/;
        else if (ECA_ALLOCMEM == status)
        Py_FatalError("initca: ca_task_initialize: ECA_ALLOCMEM\n");
        else
        Py_FatalError("initca: ca_task_initialize: unknown error code\n");
    }
    
    
}

